# Generated by Django 4.0.1 on 2022-01-12 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoLab',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('fechaInicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha Fin')),
                ('fechaEntrega', models.DateField(verbose_name='Fecha Entrega')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario que realiza el prestamo')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Filtrado.equipolab', verbose_name='Equipo Prestado')),
            ],
        ),
    ]
